version: "3.9"

services:
  elk-api:
    build: .
    image: elk-api:latest
    volumes:
      - ./logs/:/logs/
    ports:
      - "8080:8080"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
      - bootstrap.memory_lock=true
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:9200/_cat/health"]
      interval: 3s
      timeout: 3s
      retries: 10
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.7.1
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./logs/:/logs/
    depends_on:
      elasticsearch:
        condition: service_healthy

  #filebeat:
  #  image: docker.elastic.co/beats/filebeat:8.7.1
  #  depends_on:
  #    elasticsearch:
  #      condition: service_healthy
  #  volumes:
  #    - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml
  #    - ./logs/:/logs/

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/api/status"]
      interval: 3s
      timeout: 3s
      retries: 50
    ports:
      - "5601:5601"