version: "3.9"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    volumes:
      - ./logstash/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
    networks:
      - elk

  logstash:
    build:
      context: .
      dockerfile: logstash/Dockerfile
    ports:
      - 9600:9600
      - 5228:5228
    environment:
      LOGSTASH_PORT: 5228
      LOGSTASH_INDEX: "test-index"
      ELASTIC_HOST: "localhost:9200"
      #ELASTIC_USERNAME: "elastic"
      #ELASTIC_PASSWORD: "elastic"
    networks:
      - elk
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    hostname: kibana
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    environment:
      ELASTIC_HOST: "http://localhost:9200"
      #ELASTIC_USERNAME: "elastic"
      #ELASTIC_PASSWORD: "elastic"

  go-app:
    container_name: go-app
    build:
      context: .
    networks:
      - elk
    ports:
      - "8080:8080"

networks:
  elk:
    driver: bridge

volumes:
  esdata:
    driver: local